openapi: '3.0.0'
info:
  version: '1.0.4'
  title: 'Customers Service'
  description: Create or check status of customer(s)

servers:
  - url: https://40ebb7fb-afef-4781-8af5-c44607bdc062.mock.pstmn.io
  - url: https://f6f8fff3-6207-44fe-9502-737fe375b56c.mock.pstmn.io

paths:
  /customers:
    get: 
      summary: Provide a full list of users while using pagination
      responses:
        '200':
          description: The current list of customers using pagination
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Malformed request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: General error 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            
  /customers/{customerId}:
    parameters:
      - name: customerId
        description: The unique identifier of the customer
        in: path
        required: true
        schema:
          $ref: '#/components/schemas/CustomerId'
    get:
      summary: Read a customer
      responses:
        '200':
          description: The customer corresponding to the provided `customerId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        404:
          description: No spacecraft found for the provided `customerId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    CustomerId:
      description: The unique identifier of a customer
      type: string
    Spacecraft:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          $ref: '#/components/schemas/CustomerId'
        name:
          type: string
        type:
          type: string
          enum:
            - spendLevel
            - type
            - territory
            - country
            - status
        description:
          type: string
    Customers:
      description: Full list of customers using pagination
      type: object
      properties:
        id:
          $ref: '#/components/schemas/Customers'
        name:
          type: string
        type:
          type: string
          enum:
            - spendLevel
            - type
            - territory
            - country
            - status
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []
